apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
    accessControlAllowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
      - "Accept"
      - "Origin"
      - "X-User-Id"
      - "X-User-Role"
      - "X-Username"
    accessControlAllowOriginList:
      - "http://localhost:3000"
      - "http://localhost:8080"
      - "http://localhost:5173"
      - "http://phamdatzx.id.vn"
      - "https://phamdatzx.id.vn"
%{ if cloudfront_domain != "" ~}
      - "https://${cloudfront_domain}"
      - "http://${cloudfront_domain}"
%{ endif ~}
    accessControlAllowCredentials: true
    accessControlExposeHeaders:
      - "X-User-Id"
      - "X-User-Role"
      - "X-Username"
    accessControlMaxAge: 3600
    addVaryHeader: true
