apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: default
type: Opaque
data:
  PROJECT_NAME: {{ .Values.secret.PROJECT_NAME | b64enc | quote }}
  API_V1_PREFIX: {{ .Values.secret.API_V1_PREFIX | b64enc | quote }}
  VERSION: {{ .Values.secret.VERSION | b64enc | quote }}
  DEBUG: {{ .Values.secret.DEBUG | b64enc | quote }}

  QDRANT_URL: {{ .Values.secret.QDRANT_URL | b64enc | quote }}
  QDRANT_API_KEY: {{ .Values.secret.QDRANT_API_KEY | b64enc | quote }}
  QDRANT_USER_COLLECTION_NAME: {{ .Values.secret.QDRANT_USER_COLLECTION_NAME | b64enc | quote }}
  QDRANT_PRODUCT_DOC_COLLECTION: {{ .Values.secret.QDRANT_PRODUCT_DOC_COLLECTION | b64enc | quote }}

  RABBITMQ_URL: {{ .Values.secret.RABBITMQ_URL | b64enc | quote }}
  PRODUCT_CREATED_QUEUE: {{ .Values.secret.PRODUCT_CREATED_QUEUE | b64enc | quote }}
  USER_VECTOR_QUEUE: {{ .Values.secret.USER_VECTOR_QUEUE | b64enc | quote }}

  OPENAI_API_KEY: {{ .Values.secret.OPENAI_API_KEY | b64enc | quote }}
  OPENAI_MODEL: {{ .Values.secret.OPENAI_MODEL | b64enc | quote }}
  OPENAI_TEMPERATURE: {{ .Values.secret.OPENAI_TEMPERATURE | toString | b64enc | quote }}
  OPENAI_EMBEDDING_MODEL: {{ .Values.secret.OPENAI_EMBEDDING_MODEL | b64enc | quote }}

  RAG_TOP_K: {{ .Values.secret.RAG_TOP_K | toString | b64enc | quote }}
  RAG_SCORE_THRESHOLD: {{ .Values.secret.RAG_SCORE_THRESHOLD | toString | b64enc | quote }}

  MONGO_URI: {{ .Values.secret.MONGO_URI | b64enc | quote }}
  MONGO_DB_NAME: {{ .Values.secret.MONGO_DB_NAME | b64enc | quote }}
  INTERACTION_COLLECTION_NAME: {{ .Values.secret.INTERACTION_COLLECTION_NAME | b64enc | quote }}
  USER_INTERACTION_HISTORY_LIMIT: {{ .Values.secret.USER_INTERACTION_HISTORY_LIMIT | toString | b64enc | quote }}
  INTERACTION_ACTION_SCORES_JSON: {{ .Values.secret.INTERACTION_ACTION_SCORES_JSON | b64enc | quote }}
  INTERACTION_DEFAULT_SCORE: {{ .Values.secret.INTERACTION_DEFAULT_SCORE | toString | b64enc | quote }}

  PRODUCT_SERVICE_URL: {{ .Values.secret.PRODUCT_SERVICE_URL | b64enc | quote }}
  ORDER_SERVICE_URL: {{ .Values.secret.ORDER_SERVICE_URL | b64enc | quote }}

  CF_TOP_K: {{ .Values.secret.CF_TOP_K | toString | b64enc | quote }}
  CF_MIN_USER_INTERACTIONS: {{ .Values.secret.CF_MIN_USER_INTERACTIONS | toString | b64enc | quote }}
  CF_MIN_ITEM_INTERACTIONS: {{ .Values.secret.CF_MIN_ITEM_INTERACTIONS | toString | b64enc | quote }}
  CF_MAX_PRODUCTS: {{ .Values.secret.CF_MAX_PRODUCTS | toString | b64enc | quote }}
  ITEM_SIMILARITY_COLLECTION_NAME: {{ .Values.secret.ITEM_SIMILARITY_COLLECTION_NAME | b64enc | quote }}
