apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: default
type: Opaque
data:
  PROJECT_NAME: {{ .Values.secret.PROJECT_NAME | b64enc | quote }}
  API_V1_PREFIX: {{ .Values.secret.API_V1_PREFIX | b64enc | quote }}
  VERSION: {{ .Values.secret.VERSION | b64enc | quote }}
  DEBUG: {{ .Values.secret.DEBUG | b64enc | quote }}

  QDRANT_URL: {{ .Values.secret.QDRANT_URL | b64enc | quote }}
  QDRANT_API_KEY: {{ .Values.secret.QDRANT_API_KEY | b64enc | quote }}
  QDRANT_COLLECTION_NAME: {{ .Values.secret.QDRANT_COLLECTION_NAME | b64enc | quote }}
  QDRANT_USER_COLLECTION_NAME: {{ .Values.secret.QDRANT_USER_COLLECTION_NAME | b64enc | quote }}

  RABBITMQ_URL: {{ .Values.secret.RABBITMQ_URL | b64enc | quote }}
  PRODUCT_CREATED_QUEUE: {{ .Values.secret.PRODUCT_CREATED_QUEUE | b64enc | quote }}
  USER_VECTOR_QUEUE: {{ .Values.secret.USER_VECTOR_QUEUE | b64enc | quote }}

  EMBEDDING_MODEL_NAME: {{ .Values.secret.EMBEDDING_MODEL_NAME | b64enc | quote }}
  INTENT_MODEL_REPO_ID: {{ .Values.secret.INTENT_MODEL_REPO_ID | b64enc | quote }}
  INTENT_DATASET_URL: {{ .Values.secret.INTENT_DATASET_URL | b64enc | quote }}

  MONGO_URI: {{ .Values.secret.MONGO_URI | b64enc | quote }}
  MONGO_DB_NAME: {{ .Values.secret.MONGO_DB_NAME | b64enc | quote }}
  INTERACTION_COLLECTION_NAME: {{ .Values.secret.INTERACTION_COLLECTION_NAME | b64enc | quote }}
  USER_INTERACTION_HISTORY_LIMIT: {{ .Values.secret.USER_INTERACTION_HISTORY_LIMIT | toString | b64enc | quote }}
  INTERACTION_ACTION_SCORES_JSON: {{ .Values.secret.INTERACTION_ACTION_SCORES_JSON | b64enc | quote }}
  INTERACTION_DEFAULT_SCORE: {{ .Values.secret.INTERACTION_DEFAULT_SCORE | toString | b64enc | quote }}

  CF_TOP_K: {{ .Values.secret.CF_TOP_K | toString | b64enc | quote }}
  CF_MIN_USER_INTERACTIONS: {{ .Values.secret.CF_MIN_USER_INTERACTIONS | toString | b64enc | quote }}
  CF_MIN_ITEM_INTERACTIONS: {{ .Values.secret.CF_MIN_ITEM_INTERACTIONS | toString | b64enc | quote }}
  CF_MAX_PRODUCTS: {{ .Values.secret.CF_MAX_PRODUCTS | toString | b64enc | quote }}
  ITEM_SIMILARITY_COLLECTION_NAME: {{ .Values.secret.ITEM_SIMILARITY_COLLECTION_NAME | b64enc | quote }}
