apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  namespace: default
  labels:
    app: {{ .Values.appName}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      namespace: default
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
        - name: {{.Values.appName}}
          image: "{{.Values.image}}:{{.Values.tag}}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.containerPort}}
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          envFrom:
            - secretRef:
                name: {{.Values.appName}}-secret


